module.exports = {

    globals: {
        suite: true,
        test: true,
        expect: true,
        should: true
    },
    extends: [
        'eslint:recommended'
    ],
    rules: {
        'array-callback-return': 'error',
        'consistent-return': 'error',
        'default-case': 'error',
        'dot-location': ['error', 'property'],
        'dot-notation': ['error', {allowKeywords: true}],
        eqeqeq: ['error', 'always'],
        curly: 'error',
        'guard-for-in': 'error',
        'no-alert': 'error',
        'no-caller': 'error',
        'no-div-regex': 'error',
        'no-else-return': 'error',
        'no-empty-function': ['error', {allow: ['arrowFunctions']}],
        'no-eq-null': 'error',
        'no-eval': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-floating-decimal': 'error',
        'no-global-assign': 'error',
        'no-implicit-coercion': 'error',
        'no-implicit-globals': 'error',
        'no-implied-eval': 'error',
        'no-iterator': 'error',
        'no-labels': 'error',
        'no-lone-blocks': 'error',
        'no-loop-func': 'error',
        'no-magic-numbers': 'error',
        'no-multi-spaces': 'error',
        'no-multi-str': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-new': 'error',
        'no-octal-escape': 'error',
        'no-param-reassign': 'error',
        'no-proto': 'error',
        'no-return-assign': 'error',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-throw-literal': 'error',
        'no-unmodified-loop-condition': 'warn',
        'no-useless-call': 'error',
        'no-useless-concat': 'error',
        'no-useless-escape': 'error',
        'no-void': 'error',
        'no-warning-comments': ['error', {terms: ['todo', 'fixme']}],
        'no-with': 'error',
        'radix': ['error', 'as-needed'],
        'wrap-iife': ['error', 'inside'],
        'yoda': ['error', 'never'],
        'init-declarations': ['error', 'always'],
        'no-catch-shadow': 'error',
        'no-shadow-restricted-names': 'error',
        'no-shadow': 'error',
        'no-undef-init': 'error',
        'no-undefined': 'error',
        'no-use-before-define': 'error',
        'array-bracket-spacing': ['error', 'never'],
        'block-spacing': ['error', 'never'],
        'brace-style': ['error', 'stroustrup'],
        'camelcase': ['error', {properties: 'always'}],
        'comma-dangle': ['error', 'never'],
        'comma-spacing': ['error', {'before': false, 'after': true}],
        'computed-property-spacing': ['error', 'never'],
        'consistent-this': 'error',
        'eol-last': 'error',
        'func-call-spacing': ['error', 'never'],
        'func-name-matching': 'error',
        'func-style': ['error', 'declaration', {'allowArrowFunctions': true}],
        'no-template-curly-in-string': 'error',
        'no-unsafe-negation': 'error',
        semi: ['error', 'always'],
        strict: 'error'
    }
};
